// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.3 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for GroupScope.
const (
	DomainLocal GroupScope = "Domain_Local"
	Global      GroupScope = "Global"
	Universal   GroupScope = "Universal"
)

// BooleanResult defines model for BooleanResult.
type BooleanResult struct {
	Output *string `json:"output"`
	Result *bool   `json:"result,omitempty"`
}

// Computer defines model for Computer.
type Computer struct {
	ComputerName    *string `json:"computerName"`
	Created         *string `json:"created"`
	Description     *string `json:"description"`
	DnsName         *string `json:"dnsName"`
	OperatingSystem *string `json:"operatingSystem"`
	Path            *string `json:"path"`
	Sid             *string `json:"sid"`
}

// ComputerListResult defines model for ComputerListResult.
type ComputerListResult struct {
	Output *string     `json:"output"`
	Result *[]Computer `json:"result"`
}

// ComputerResult defines model for ComputerResult.
type ComputerResult struct {
	Output *string   `json:"output"`
	Result *Computer `json:"result,omitempty"`
}

// DateTimeResult defines model for DateTimeResult.
type DateTimeResult struct {
	Output *string    `json:"output"`
	Result *time.Time `json:"result"`
}

// DnsRecord defines model for DnsRecord.
type DnsRecord struct {
	Data      *string `json:"data"`
	Name      *string `json:"name"`
	Timestamp *string `json:"timestamp"`
	Type      *string `json:"type"`
	Zone      *string `json:"zone"`
}

// DnsRecordListResult defines model for DnsRecordListResult.
type DnsRecordListResult struct {
	Output *string      `json:"output"`
	Result *[]DnsRecord `json:"result"`
}

// DnsRecordResult defines model for DnsRecordResult.
type DnsRecordResult struct {
	Output *string    `json:"output"`
	Result *DnsRecord `json:"result,omitempty"`
}

// DnsZone defines model for DnsZone.
type DnsZone struct {
	DistinguishedName *string `json:"distinguishedName"`
	Type              *string `json:"type"`
	ZoneName          *string `json:"zoneName"`
	ZoneType          *string `json:"zoneType"`
}

// DnsZoneListResult defines model for DnsZoneListResult.
type DnsZoneListResult struct {
	Output *string    `json:"output"`
	Result *[]DnsZone `json:"result"`
}

// DnsZoneResult defines model for DnsZoneResult.
type DnsZoneResult struct {
	Output *string  `json:"output"`
	Result *DnsZone `json:"result,omitempty"`
}

// Group defines model for Group.
type Group struct {
	Description *string             `json:"description"`
	Email       *string             `json:"email"`
	Guid        *openapi_types.UUID `json:"guid,omitempty"`
	Name        *string             `json:"name"`
	OuPath      *string             `json:"ouPath"`
	Scope       *GroupScope         `json:"scope,omitempty"`
	Type        *string             `json:"type"`
}

// GroupListResult defines model for GroupListResult.
type GroupListResult struct {
	Output *string  `json:"output"`
	Result *[]Group `json:"result"`
}

// GroupResult defines model for GroupResult.
type GroupResult struct {
	Output *string `json:"output"`
	Result *Group  `json:"result,omitempty"`
}

// GroupScope defines model for GroupScope.
type GroupScope string

// OU defines model for OU.
type OU struct {
	Description *string             `json:"description"`
	Guid        *openapi_types.UUID `json:"guid,omitempty"`
	Name        *string             `json:"name"`
	Path        *string             `json:"path"`
	Protected   *bool               `json:"protected,omitempty"`
}

// OUListResult defines model for OUListResult.
type OUListResult struct {
	Output *string `json:"output"`
	Result *[]OU   `json:"result"`
}

// OUResult defines model for OUResult.
type OUResult struct {
	Output *string `json:"output"`
	Result *OU     `json:"result,omitempty"`
}

// StringResult defines model for StringResult.
type StringResult struct {
	Output *string `json:"output"`
	Result *string `json:"result"`
}

// User defines model for User.
type User struct {
	IncludeAllProperties    *bool     `json:"_IncludeAllProperties,omitempty"`
	ShowFields              *[]string `json:"_ShowFields"`
	ChangePasswordNextLogon *bool     `json:"changePasswordNextLogon,omitempty"`
	City                    *string   `json:"city"`
	Company                 *string   `json:"company"`
	Country                 *string   `json:"country"`
	Department              *string   `json:"department"`
	Description             *string   `json:"description"`
	DisplayName             *string   `json:"displayName"`
	EmailAddress            *string   `json:"emailAddress"`
	FirstName               *string   `json:"firstName"`
	HomeFolderDirectory     *string   `json:"homeFolderDirectory"`
	HomeFolderDrive         *string   `json:"homeFolderDrive"`
	HomeFolderPath          *string   `json:"homeFolderPath"`
	HomePhone               *string   `json:"homePhone"`
	Initials                *string   `json:"initials"`
	JobTitle                *string   `json:"jobTitle"`
	LastName                *string   `json:"lastName"`
	Manager                 *string   `json:"manager"`
	MobilePhone             *string   `json:"mobilePhone"`
	Office                  *string   `json:"office"`
	OfficePhone             *string   `json:"officePhone"`
	OuPath                  *string   `json:"ouPath"`
	PostalCode              *string   `json:"postalCode"`
	ProfileLogonScript      *string   `json:"profileLogonScript"`
	ProfilePath             *string   `json:"profilePath"`
	RdsAllowLogon           *bool     `json:"rdsAllowLogon,omitempty"`
	RdsConnectDrive         *bool     `json:"rdsConnectDrive,omitempty"`
	RdsHomeFolderDrive      *string   `json:"rdsHomeFolderDrive"`
	RdsHomeFolderPath       *string   `json:"rdsHomeFolderPath"`
	RdsProfilePath          *string   `json:"rdsProfilePath"`
	SamUsername             *string   `json:"samUsername"`
	State                   *string   `json:"state"`
	StreetAddress           *string   `json:"streetAddress"`
	StreetPoBox             *string   `json:"streetPoBox"`
	Username                *string   `json:"username"`
}

// UserListResult defines model for UserListResult.
type UserListResult struct {
	Output *string `json:"output"`
	Result *[]User `json:"result"`
}

// UserResult defines model for UserResult.
type UserResult struct {
	Output *string `json:"output"`
	Result *User   `json:"result,omitempty"`
}

// GetApiADGroupsParams defines parameters for GetApiADGroups.
type GetApiADGroupsParams struct {
	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// Recursive Recursive Search
	Recursive *bool `form:"Recursive,omitempty" json:"Recursive,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADGroupsAllParams defines parameters for GetApiADGroupsAll.
type GetApiADGroupsAllParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADGroupsDistributionAllParams defines parameters for GetApiADGroupsDistributionAll.
type GetApiADGroupsDistributionAllParams struct {
	// OUPath Inside Organization Unit DN Path (Optional)
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// Recursive Recursive Search
	Recursive *bool `form:"Recursive,omitempty" json:"Recursive,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADGroupsSecurityAllParams defines parameters for GetApiADGroupsSecurityAll.
type GetApiADGroupsSecurityAllParams struct {
	// OUPath Inside Organization Unit DN Path (Optional)
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// Recursive Recursive Search
	Recursive *bool `form:"Recursive,omitempty" json:"Recursive,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADGroupsGroupNameParams defines parameters for GetApiADGroupsGroupName.
type GetApiADGroupsGroupNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADGroupsGroupNameDistributionParams defines parameters for PostApiADGroupsGroupNameDistribution.
type PostApiADGroupsGroupNameDistributionParams struct {
	// GroupScope AD Group Scope
	GroupScope *GroupScope `form:"GroupScope,omitempty" json:"GroupScope,omitempty"`

	// GroupDescription AD Group Description
	GroupDescription *string `form:"GroupDescription,omitempty" json:"GroupDescription,omitempty"`

	// GroupEmail AD Group Email
	GroupEmail *string `form:"GroupEmail,omitempty" json:"GroupEmail,omitempty"`

	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADGroupsGroupNameExistsParams defines parameters for GetApiADGroupsGroupNameExists.
type GetApiADGroupsGroupNameExistsParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiADGroupsGroupNameRemoveParams defines parameters for DeleteApiADGroupsGroupNameRemove.
type DeleteApiADGroupsGroupNameRemoveParams struct {
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiADGroupsGroupNameRenameNewGroupNameParams defines parameters for PutApiADGroupsGroupNameRenameNewGroupName.
type PutApiADGroupsGroupNameRenameNewGroupNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADGroupsGroupNameSecurityParams defines parameters for PostApiADGroupsGroupNameSecurity.
type PostApiADGroupsGroupNameSecurityParams struct {
	// GroupScope AD Group Scope
	GroupScope *GroupScope `form:"GroupScope,omitempty" json:"GroupScope,omitempty"`

	// GroupDescription AD Group Description
	GroupDescription *string `form:"GroupDescription,omitempty" json:"GroupDescription,omitempty"`

	// GroupEmail AD Group Email
	GroupEmail *string `form:"GroupEmail,omitempty" json:"GroupEmail,omitempty"`

	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// APIUserParams defines parameters for APIUser.
type APIUserParams struct {
	// Username AD User Name
	Username *string `form:"Username,omitempty" json:"Username,omitempty"`

	// Password User Password
	Password *string `form:"Password,omitempty" json:"Password,omitempty"`

	// FirstName AD User First Name
	FirstName *string `form:"FirstName,omitempty" json:"FirstName,omitempty"`

	// Initials AD User Initials
	Initials *string `form:"Initials,omitempty" json:"Initials,omitempty"`

	// LastName AD User LastName
	LastName *string `form:"LastName,omitempty" json:"LastName,omitempty"`

	// DisplayName User DisplayName
	DisplayName *string `form:"DisplayName,omitempty" json:"DisplayName,omitempty"`

	// Description User Description
	Description *string `form:"Description,omitempty" json:"Description,omitempty"`

	// EmailAddress User Email Address
	EmailAddress *string `form:"EmailAddress,omitempty" json:"EmailAddress,omitempty"`

	// Department User Department
	Department *string `form:"Department,omitempty" json:"Department,omitempty"`

	// Office User Office
	Office *string `form:"Office,omitempty" json:"Office,omitempty"`

	// Company User Company
	Company *string `form:"Company,omitempty" json:"Company,omitempty"`

	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// ChangePasswordNextLogon User Must Change Password at Next Logon
	ChangePasswordNextLogon *bool `form:"ChangePasswordNextLogon,omitempty" json:"ChangePasswordNextLogon,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiADUserParams defines parameters for PutApiADUser.
type PutApiADUserParams struct {
	// Username AD User Name
	Username *string `form:"Username,omitempty" json:"Username,omitempty"`

	// FirstName AD User First Name
	FirstName *string `form:"FirstName,omitempty" json:"FirstName,omitempty"`

	// Initials AD User Initials
	Initials *string `form:"Initials,omitempty" json:"Initials,omitempty"`

	// LastName AD User LastName
	LastName *string `form:"LastName,omitempty" json:"LastName,omitempty"`

	// DisplayName User DisplayName
	DisplayName *string `form:"DisplayName,omitempty" json:"DisplayName,omitempty"`

	// Description User Description
	Description *string `form:"Description,omitempty" json:"Description,omitempty"`

	// EmailAddress User Email Address
	EmailAddress *string `form:"EmailAddress,omitempty" json:"EmailAddress,omitempty"`

	// Department User Department
	Department *string `form:"Department,omitempty" json:"Department,omitempty"`

	// Office User Office
	Office *string `form:"Office,omitempty" json:"Office,omitempty"`

	// Company User Company
	Company *string `form:"Company,omitempty" json:"Company,omitempty"`

	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// ChangePasswordNextLogon User Must Change Password at Next Logon
	ChangePasswordNextLogon *bool `form:"ChangePasswordNextLogon,omitempty" json:"ChangePasswordNextLogon,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADUserListUsersParams defines parameters for GetApiADUserListUsers.
type GetApiADUserListUsersParams struct {
	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// Recursive Recursive Search
	Recursive *bool `form:"Recursive,omitempty" json:"Recursive,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADUserListUsersAllParams defines parameters for GetApiADUserListUsersAll.
type GetApiADUserListUsersAllParams struct {
	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiADUserUsernameParams defines parameters for DeleteApiADUserUsername.
type DeleteApiADUserUsernameParams struct {
	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADUserUsernameParams defines parameters for GetApiADUserUsername.
type GetApiADUserUsernameParams struct {
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameAddressParams defines parameters for PostApiADUserUsernameAddress.
type PostApiADUserUsernameAddressParams struct {
	// Street User Street
	Street *string `form:"Street,omitempty" json:"Street,omitempty"`

	// POBox User P.O. Box
	POBox *string `form:"POBox,omitempty" json:"POBox,omitempty"`

	// City User City
	City *string `form:"City,omitempty" json:"City,omitempty"`

	// State User State/Province
	State *string `form:"State,omitempty" json:"State,omitempty"`

	// ZipCode User Zip/Postal Code
	ZipCode *string `form:"ZipCode,omitempty" json:"ZipCode,omitempty"`

	// Country User Country/Region Code
	Country *string `form:"Country,omitempty" json:"Country,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameAddressClearParams defines parameters for PostApiADUserUsernameAddressClear.
type PostApiADUserUsernameAddressClearParams struct {
	// ClearStreet User Street
	ClearStreet *bool `form:"ClearStreet,omitempty" json:"ClearStreet,omitempty"`

	// ClearPOBox User P.O. Box
	ClearPOBox *bool `form:"ClearPOBox,omitempty" json:"ClearPOBox,omitempty"`

	// ClearCity User City
	ClearCity *bool `form:"ClearCity,omitempty" json:"ClearCity,omitempty"`

	// ClearState User State/Province
	ClearState *bool `form:"ClearState,omitempty" json:"ClearState,omitempty"`

	// ClearZipCode User Zip/Postal Code
	ClearZipCode *bool `form:"ClearZipCode,omitempty" json:"ClearZipCode,omitempty"`

	// ClearCountry User Country/Region Code
	ClearCountry *bool `form:"ClearCountry,omitempty" json:"ClearCountry,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiADUserUsernameDisableParams defines parameters for PutApiADUserUsernameDisable.
type PutApiADUserUsernameDisableParams struct {
	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiADUserUsernameEnableParams defines parameters for PutApiADUserUsernameEnable.
type PutApiADUserUsernameEnableParams struct {
	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADUserUsernameExistsParams defines parameters for GetApiADUserUsernameExists.
type GetApiADUserUsernameExistsParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADUserUsernameGroupAllParams defines parameters for GetApiADUserUsernameGroupAll.
type GetApiADUserUsernameGroupAllParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiADUserUsernameGroupGroupNameParams defines parameters for DeleteApiADUserUsernameGroupGroupName.
type DeleteApiADUserUsernameGroupGroupNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADUserUsernameGroupGroupNameParams defines parameters for GetApiADUserUsernameGroupGroupName.
type GetApiADUserUsernameGroupGroupNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameGroupGroupNameParams defines parameters for PostApiADUserUsernameGroupGroupName.
type PostApiADUserUsernameGroupGroupNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADUserUsernameGroupGroupNameExistsParams defines parameters for GetApiADUserUsernameGroupGroupNameExists.
type GetApiADUserUsernameGroupGroupNameExistsParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiADUserUsernameLastLogonParams defines parameters for GetApiADUserUsernameLastLogon.
type GetApiADUserUsernameLastLogonParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameOrganizationParams defines parameters for PostApiADUserUsernameOrganization.
type PostApiADUserUsernameOrganizationParams struct {
	// JobTitle User Job Title
	JobTitle *string `form:"JobTitle,omitempty" json:"JobTitle,omitempty"`

	// Department User Department
	Department *string `form:"Department,omitempty" json:"Department,omitempty"`

	// Company User Company
	Company *string `form:"Company,omitempty" json:"Company,omitempty"`

	// Manager User Manager
	Manager *string `form:"Manager,omitempty" json:"Manager,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameOrganizationClearParams defines parameters for PostApiADUserUsernameOrganizationClear.
type PostApiADUserUsernameOrganizationClearParams struct {
	// ClearJobTitle User Job Title
	ClearJobTitle *bool `form:"ClearJobTitle,omitempty" json:"ClearJobTitle,omitempty"`

	// ClearDepartment User Department
	ClearDepartment *bool `form:"ClearDepartment,omitempty" json:"ClearDepartment,omitempty"`

	// ClearCompany User Company
	ClearCompany *bool `form:"ClearCompany,omitempty" json:"ClearCompany,omitempty"`

	// ClearManager User Manager
	ClearManager *bool `form:"ClearManager,omitempty" json:"ClearManager,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernamePhoneParams defines parameters for PostApiADUserUsernamePhone.
type PostApiADUserUsernamePhoneParams struct {
	// OfficePhone User Office Phone
	OfficePhone *string `form:"OfficePhone,omitempty" json:"OfficePhone,omitempty"`

	// HomePhone User Home Phone
	HomePhone *string `form:"HomePhone,omitempty" json:"HomePhone,omitempty"`

	// MobilePhone User Mobile Phone
	MobilePhone *string `form:"MobilePhone,omitempty" json:"MobilePhone,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernamePhoneClearParams defines parameters for PostApiADUserUsernamePhoneClear.
type PostApiADUserUsernamePhoneClearParams struct {
	// ClearOfficePhone User Office Phone
	ClearOfficePhone *bool `form:"ClearOfficePhone,omitempty" json:"ClearOfficePhone,omitempty"`

	// ClearHomePhone User Home Phone
	ClearHomePhone *bool `form:"ClearHomePhone,omitempty" json:"ClearHomePhone,omitempty"`

	// ClearMobilePhone User Mobile Phone
	ClearMobilePhone *bool `form:"ClearMobilePhone,omitempty" json:"ClearMobilePhone,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameProfileParams defines parameters for PostApiADUserUsernameProfile.
type PostApiADUserUsernameProfileParams struct {
	// ProfilePath User Profile Path
	ProfilePath *string `form:"ProfilePath,omitempty" json:"ProfilePath,omitempty"`

	// ProfileLogonScript User Profile Logon Script
	ProfileLogonScript *string `form:"ProfileLogonScript,omitempty" json:"ProfileLogonScript,omitempty"`

	// HomeFolderPath User Home Folder Path
	HomeFolderPath *string `form:"HomeFolderPath,omitempty" json:"HomeFolderPath,omitempty"`

	// HomeFolderDrive User Home Folder Drive
	HomeFolderDrive *string `form:"HomeFolderDrive,omitempty" json:"HomeFolderDrive,omitempty"`

	// HomeFolderDirectory User Home Folder Directory
	HomeFolderDirectory *string `form:"HomeFolderDirectory,omitempty" json:"HomeFolderDirectory,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameProfileClearParams defines parameters for PostApiADUserUsernameProfileClear.
type PostApiADUserUsernameProfileClearParams struct {
	// ClearProfilePath User Profile Path
	ClearProfilePath *bool `form:"ClearProfilePath,omitempty" json:"ClearProfilePath,omitempty"`

	// ClearProfileLogonScript User Profile Logon Script
	ClearProfileLogonScript *bool `form:"ClearProfileLogonScript,omitempty" json:"ClearProfileLogonScript,omitempty"`

	// ClearHomeFolderPath User Home Folder Path
	ClearHomeFolderPath *bool `form:"ClearHomeFolderPath,omitempty" json:"ClearHomeFolderPath,omitempty"`

	// ClearHomeFolderDrive User Home Folder Drive
	ClearHomeFolderDrive *bool `form:"ClearHomeFolderDrive,omitempty" json:"ClearHomeFolderDrive,omitempty"`

	// ClearHomeFolderDirectory User Home Folder Directory
	ClearHomeFolderDirectory *bool `form:"ClearHomeFolderDirectory,omitempty" json:"ClearHomeFolderDirectory,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameRDSProfileParams defines parameters for PostApiADUserUsernameRDSProfile.
type PostApiADUserUsernameRDSProfileParams struct {
	// ProfilePath User Remote Desktop Services Profile Path
	ProfilePath *string `form:"ProfilePath,omitempty" json:"ProfilePath,omitempty"`

	// HomeFolderPath User Remote Desktop Services Home Folder Path
	HomeFolderPath *string `form:"HomeFolderPath,omitempty" json:"HomeFolderPath,omitempty"`

	// HomeFolderDrive User Remote Desktop Services Home Folder Drive
	HomeFolderDrive *string `form:"HomeFolderDrive,omitempty" json:"HomeFolderDrive,omitempty"`

	// ConnectDrive Connect Drive
	ConnectDrive *bool `form:"ConnectDrive,omitempty" json:"ConnectDrive,omitempty"`

	// AllowLogon Allow User Logon to Remote Desktop Services
	AllowLogon *bool `form:"AllowLogon,omitempty" json:"AllowLogon,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameRDSProfileClearParams defines parameters for PostApiADUserUsernameRDSProfileClear.
type PostApiADUserUsernameRDSProfileClearParams struct {
	// ClearProfilePath User Remote Desktop Services Profile Path
	ClearProfilePath *bool `form:"ClearProfilePath,omitempty" json:"ClearProfilePath,omitempty"`

	// ClearHomeFolderPath User Remote Desktop Services Home Folder Path
	ClearHomeFolderPath *bool `form:"ClearHomeFolderPath,omitempty" json:"ClearHomeFolderPath,omitempty"`

	// ConnectDrive Connect Drive
	ConnectDrive *bool `form:"ConnectDrive,omitempty" json:"ConnectDrive,omitempty"`

	// AllowLogon Allow User Logon to Remote Desktop Services
	AllowLogon *bool `form:"AllowLogon,omitempty" json:"AllowLogon,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiADUserUsernameRenameNewUsernameParams defines parameters for PutApiADUserUsernameRenameNewUsername.
type PutApiADUserUsernameRenameNewUsernameParams struct {
	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiADUserUsernameResetPasswordParams defines parameters for PostApiADUserUsernameResetPassword.
type PostApiADUserUsernameResetPasswordParams struct {
	// NewPassword New User Password
	NewPassword *string `form:"newPassword,omitempty" json:"newPassword,omitempty"`

	// ChangePassword Force User to Change Password on Next Login
	ChangePassword *bool `form:"ChangePassword,omitempty" json:"ChangePassword,omitempty"`

	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiADUserUsernameUnlockParams defines parameters for PutApiADUserUsernameUnlock.
type PutApiADUserUsernameUnlockParams struct {
	// ShowFields User Fields to show. Optional argument, a comma-separated string, with the name of the fields you want returned.
	ShowFields *string `form:"ShowFields,omitempty" json:"ShowFields,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiComputersParams defines parameters for GetApiComputers.
type GetApiComputersParams struct {
	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// Recursive Recursive Search
	Recursive *bool `form:"Recursive,omitempty" json:"Recursive,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiComputersAllParams defines parameters for GetApiComputersAll.
type GetApiComputersAllParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiComputersCleanUpParams defines parameters for DeleteApiComputersCleanUp.
type DeleteApiComputersCleanUpParams struct {
	// Days Number of Inactive Days
	Days *int32 `form:"Days,omitempty" json:"Days,omitempty"`

	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// Recursive Recursive Search
	Recursive *bool `form:"Recursive,omitempty" json:"Recursive,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiComputersRemoveParams defines parameters for DeleteApiComputersRemove.
type DeleteApiComputersRemoveParams struct {
	// WildCard Wild Card for AD Computer Name
	WildCard *string `form:"WildCard,omitempty" json:"WildCard,omitempty"`

	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// Recursive Recursive Search
	Recursive *bool `form:"Recursive,omitempty" json:"Recursive,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiComputersADComputerNameParams defines parameters for GetApiComputersADComputerName.
type GetApiComputersADComputerNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiComputersADComputerNameExistsParams defines parameters for GetApiComputersADComputerNameExists.
type GetApiComputersADComputerNameExistsParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiComputersADComputerNameRegisterParams defines parameters for PostApiComputersADComputerNameRegister.
type PostApiComputersADComputerNameRegisterParams struct {
	// ADComputerDescription AD Computer Description (Optional)
	ADComputerDescription *string `form:"ADComputerDescription,omitempty" json:"ADComputerDescription,omitempty"`

	// OUPath Organization Unit DN Path
	OUPath *string `form:"OUPath,omitempty" json:"OUPath,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiComputersADComputerNameRemoveParams defines parameters for DeleteApiComputersADComputerNameRemove.
type DeleteApiComputersADComputerNameRemoveParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiComputersADComputerNameRenameNewADComputerNameParams defines parameters for PutApiComputersADComputerNameRenameNewADComputerName.
type PutApiComputersADComputerNameRenameNewADComputerNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiComputersADComputerNameUpdateParams defines parameters for PutApiComputersADComputerNameUpdate.
type PutApiComputersADComputerNameUpdateParams struct {
	// ComputerDescription AD Computer Description
	ComputerDescription *string `form:"ComputerDescription,omitempty" json:"ComputerDescription,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiDnsAAAARecordParams defines parameters for DeleteApiDnsAAAARecord.
type DeleteApiDnsAAAARecordParams struct {
	DNSHostName *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`
	IPv6Address *string `form:"IPv6_Address,omitempty" json:"IPv6_Address,omitempty"`
	ZoneName    *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsAAAARecordParams defines parameters for GetApiDnsAAAARecord.
type GetApiDnsAAAARecordParams struct {
	// DNSHostName DNS Hostname
	DNSHostName *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`

	// IPv6Address IPv6 Address
	IPv6Address *string `form:"IPv6_Address,omitempty" json:"IPv6_Address,omitempty"`

	// ZoneName DNS Zone Name
	ZoneName *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiDnsAAAARecordParams defines parameters for PostApiDnsAAAARecord.
type PostApiDnsAAAARecordParams struct {
	DNSHostName *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`
	IPv6Address *string `form:"IPv6_Address,omitempty" json:"IPv6_Address,omitempty"`
	ZoneName    *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsAAAARecordAllParams defines parameters for GetApiDnsAAAARecordAll.
type GetApiDnsAAAARecordAllParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsAAAARecordHostNameDNSHostNameParams defines parameters for GetApiDnsAAAARecordHostNameDNSHostName.
type GetApiDnsAAAARecordHostNameDNSHostNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsAAAARecordIPv6AddressIPv6AddressParams defines parameters for GetApiDnsAAAARecordIPv6AddressIPv6Address.
type GetApiDnsAAAARecordIPv6AddressIPv6AddressParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsAAAARecordZoneNameParams defines parameters for GetApiDnsAAAARecordZoneName.
type GetApiDnsAAAARecordZoneNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiDnsARecordParams defines parameters for DeleteApiDnsARecord.
type DeleteApiDnsARecordParams struct {
	DNSHostName *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`
	IPAddress   *string `form:"IP_Address,omitempty" json:"IP_Address,omitempty"`
	ZoneName    *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsARecordParams defines parameters for GetApiDnsARecord.
type GetApiDnsARecordParams struct {
	// DNSHostName DNS Hostname
	DNSHostName *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`

	// IPAddress IP Address
	IPAddress *string `form:"IP_Address,omitempty" json:"IP_Address,omitempty"`

	// ZoneName DNS Zone Name (Optional)
	ZoneName *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiDnsARecordParams defines parameters for PostApiDnsARecord.
type PostApiDnsARecordParams struct {
	DNSHostName *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`
	IPAddress   *string `form:"IP_Address,omitempty" json:"IP_Address,omitempty"`
	ZoneName    *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsARecordAllParams defines parameters for GetApiDnsARecordAll.
type GetApiDnsARecordAllParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsARecordHostNameDNSHostNameParams defines parameters for GetApiDnsARecordHostNameDNSHostName.
type GetApiDnsARecordHostNameDNSHostNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsARecordIPAddressIPAddressParams defines parameters for GetApiDnsARecordIPAddressIPAddress.
type GetApiDnsARecordIPAddressIPAddressParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsARecordZoneNameParams defines parameters for GetApiDnsARecordZoneName.
type GetApiDnsARecordZoneNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiDnsCNameRecordParams defines parameters for DeleteApiDnsCNameRecord.
type DeleteApiDnsCNameRecordParams struct {
	DNSHostName      *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`
	DNSHostNameAlias *string `form:"DNS_HostName_Alias,omitempty" json:"DNS_HostName_Alias,omitempty"`
	ZoneName         *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsCNameRecordParams defines parameters for GetApiDnsCNameRecord.
type GetApiDnsCNameRecordParams struct {
	// DNSHostName DNS Host NAme
	DNSHostName *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`

	// DNSHostNameAlias DNS Host Name Alias
	DNSHostNameAlias *string `form:"DNS_HostName_Alias,omitempty" json:"DNS_HostName_Alias,omitempty"`

	// ZoneName DNS Zone NAme
	ZoneName *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiDnsCNameRecordParams defines parameters for PostApiDnsCNameRecord.
type PostApiDnsCNameRecordParams struct {
	DNSHostName      *string `form:"DNS_HostName,omitempty" json:"DNS_HostName,omitempty"`
	DNSHostNameAlias *string `form:"DNS_HostName_Alias,omitempty" json:"DNS_HostName_Alias,omitempty"`
	ZoneName         *string `form:"ZoneName,omitempty" json:"ZoneName,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsCNameRecordAllParams defines parameters for GetApiDnsCNameRecordAll.
type GetApiDnsCNameRecordAllParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsCNameRecordHostNameDNSHostNameParams defines parameters for GetApiDnsCNameRecordHostNameDNSHostName.
type GetApiDnsCNameRecordHostNameDNSHostNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsCNameRecordHostNameAliasDNSHostNameAliasParams defines parameters for GetApiDnsCNameRecordHostNameAliasDNSHostNameAlias.
type GetApiDnsCNameRecordHostNameAliasDNSHostNameAliasParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsCNameRecordZoneNameParams defines parameters for GetApiDnsCNameRecordZoneName.
type GetApiDnsCNameRecordZoneNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsLookupZoneAllParams defines parameters for GetApiDnsLookupZoneAll.
type GetApiDnsLookupZoneAllParams struct {
	// IgnoreSystemZones Ignore System Zones
	IgnoreSystemZones *bool `form:"IgnoreSystemZones,omitempty" json:"IgnoreSystemZones,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiDnsLookupZoneZoneNameParams defines parameters for DeleteApiDnsLookupZoneZoneName.
type DeleteApiDnsLookupZoneZoneNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiDnsLookupZoneZoneNameParams defines parameters for PostApiDnsLookupZoneZoneName.
type PostApiDnsLookupZoneZoneNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsReverseLookupZoneAllParams defines parameters for GetApiDnsReverseLookupZoneAll.
type GetApiDnsReverseLookupZoneAllParams struct {
	// IgnoreSystemZones Ignore System Zones
	IgnoreSystemZones *bool `form:"IgnoreSystemZones,omitempty" json:"IgnoreSystemZones,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiDnsReverseLookupZoneNetworkIDOrZoneNameParams defines parameters for DeleteApiDnsReverseLookupZoneNetworkIDOrZoneName.
type DeleteApiDnsReverseLookupZoneNetworkIDOrZoneNameParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsReverseLookupZoneNetworkIDOrZoneNameParams defines parameters for GetApiDnsReverseLookupZoneNetworkIDOrZoneName.
type GetApiDnsReverseLookupZoneNetworkIDOrZoneNameParams struct {
	// IgnoreSystemZones Ignore System Zones
	IgnoreSystemZones *bool `form:"IgnoreSystemZones,omitempty" json:"IgnoreSystemZones,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiDnsReverseLookupZoneNetworkIDParams defines parameters for PostApiDnsReverseLookupZoneNetworkID.
type PostApiDnsReverseLookupZoneNetworkIDParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsZonesAllParams defines parameters for GetApiDnsZonesAll.
type GetApiDnsZonesAllParams struct {
	// IgnoreSystemZones Ignore System Zones
	IgnoreSystemZones *bool `form:"IgnoreSystemZones,omitempty" json:"IgnoreSystemZones,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsZonesZoneNameParams defines parameters for GetApiDnsZonesZoneName.
type GetApiDnsZonesZoneNameParams struct {
	// IgnoreSystemZones Ignore System Zones
	IgnoreSystemZones *bool `form:"IgnoreSystemZones,omitempty" json:"IgnoreSystemZones,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiDnsZonesZoneNameExistsParams defines parameters for GetApiDnsZonesZoneNameExists.
type GetApiDnsZonesZoneNameExistsParams struct {
	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PostApiLoginParams defines parameters for PostApiLogin.
type PostApiLoginParams struct {
	// Username AD user name
	Username *string `form:"username,omitempty" json:"username,omitempty"`

	// Password AD user password
	Password *string `form:"password,omitempty" json:"password,omitempty"`
}

// PostApiOUParams defines parameters for PostApiOU.
type PostApiOUParams struct {
	// OUName Organization Unit Name
	OUName string `form:"OUName" json:"OUName"`

	// OUDescription Organization Unit Description
	OUDescription *string `form:"OUDescription,omitempty" json:"OUDescription,omitempty"`

	// OUDestinationPath Destination Organization Unit DN Path (Parent)
	OUDestinationPath string `form:"OUDestinationPath" json:"OUDestinationPath"`

	// IsProtected Protect Organization Unit from Accidental Deletion
	IsProtected *bool `form:"IsProtected,omitempty" json:"IsProtected,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiOUParams defines parameters for PutApiOU.
type PutApiOUParams struct {
	// OUPath Organization Unit DN Path
	OUPath string `form:"OUPath" json:"OUPath"`

	// OUDescription Organization Unit Description
	OUDescription *string `form:"OUDescription,omitempty" json:"OUDescription,omitempty"`

	// IsProtected Protect Organization Unit from Accidental Deletion
	IsProtected *bool `form:"IsProtected,omitempty" json:"IsProtected,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiOUAllParams defines parameters for GetApiOUAll.
type GetApiOUAllParams struct {
	// ListContainers List All AD Containers, Including Hidden and System Containers
	ListContainers *bool `form:"ListContainers,omitempty" json:"ListContainers,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetOUByGuidParams defines parameters for GetOUByGuid.
type GetOUByGuidParams struct {
	// OUGuid Organization Unit Guid
	OUGuid openapi_types.UUID `form:"OUGuid" json:"OUGuid"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiOUMoveParams defines parameters for PutApiOUMove.
type PutApiOUMoveParams struct {
	// OUPath Organization Unit DN Path
	OUPath string `form:"OUPath" json:"OUPath"`

	// OUDestinationPath Destination Organization DN Path (New Parent OU)
	OUDestinationPath string `form:"OUDestinationPath" json:"OUDestinationPath"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetOUByPathParams defines parameters for GetOUByPath.
type GetOUByPathParams struct {
	// OUPath Organization Unit DN Path
	OUPath string `form:"OUPath" json:"OUPath"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// GetApiOUPathExistsParams defines parameters for GetApiOUPathExists.
type GetApiOUPathExistsParams struct {
	// OUPath Organization Unit DN Path
	OUPath string `form:"OUPath" json:"OUPath"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// DeleteApiOUPathRemoveParams defines parameters for DeleteApiOUPathRemove.
type DeleteApiOUPathRemoveParams struct {
	// OUPath Organization Unit DN Path
	OUPath string `form:"OUPath" json:"OUPath"`

	// Force Force Deletion of Protected Organization Unit
	Force *bool `form:"Force,omitempty" json:"Force,omitempty"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}

// PutApiOURenameParams defines parameters for PutApiOURename.
type PutApiOURenameParams struct {
	// OUPath Organization Unit DN Path
	OUPath string `form:"OUPath" json:"OUPath"`

	// OUNewName Organization Unit New Name
	OUNewName string `form:"OUNewName" json:"OUNewName"`

	// AuthToken Bearer or Basic Authentication Token
	AuthToken string `json:"Auth-Token"`
}
